### ISSUE TITLE
Add button to open config in text editor upon first startup

### ISSUE THREAD

**Issue by Beyley** [LittleBigRefresh/FreshPresence#1]
Right now it just tells you the filename and tells you to edit it, but we should have a button to open it in a system installed text editor, whether it be notepad on windows, or on linux where we just have a list of like 20 to try in order

**Comment by jvyden** [comment]
Why not just have the OS handle picking the text editor? You can use `xdg-open` for Linux, `open` on macOS, and passing the file directly for Windows,
