### ISSUE TITLE
Windows' cmd doesn't support vt100 color codes

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/FreshPresence#4]

**Comment by jvyden** [comment]
![image](https://github.com/LittleBigRefresh/FreshPresence/assets/40577357/d85452ca-8290-42a5-8a11-fe104b306f24)

**Comment by Beyley** [comment]
i believe this is already resolved
https://github.com/LittleBigRefresh/FreshPresence/blob/f7c4169318ce6c2f17b03b13f54147e2cf63fc9c/src/main.zig#L31-L35
